# -*- coding: utf-8 -*-
"""Saudi_Event_AI_Photo_Booth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10T0dQghjvOj63MHe_tn8FzD-Mt3Nec7D
"""

import os

# 1. Create target directory if it doesn't exist
os.makedirs("experiments/pretrained_models", exist_ok=True)

# 2. Download GFPGAN v1.4 model weights
!wget https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth -P experiments/pretrained_models/

import sys
import os
import torchvision.transforms.functional as F

# Fix 1: Redirect deprecated torchvision import
sys.modules["torchvision.transforms.functional_tensor"] = F

# Fix 2: Download GFPGANv1.4 weights if not already present
weights_path = "experiments/pretrained_models/GFPGANv1.4.pth"
if not os.path.exists(weights_path):
    os.makedirs("experiments/pretrained_models", exist_ok=True)
    !wget https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth -P experiments/pretrained_models/

from gfpgan import GFPGANer

# Initialize GFPGAN Restorer
restorer = GFPGANer(
    model_path=weights_path,
    upscale=2,
    arch="clean",
    channel_multiplier=2,
    bg_upsampler=None,
)

print("GFPGAN Restorer initialized successfully!")

import sys
import torchvision.transforms.functional as F

# Redirect the deprecated import path to the current torchvision module
sys.modules["torchvision.transforms.functional_tensor"] = F

# Now import GFPGAN as normal
from gfpgan import GFPGANer

# Initialize GFPGAN Restorer
restorer = GFPGANer(
    model_path="experiments/pretrained_models/GFPGANv1.4.pth",
    upscale=2,
    arch="clean",
    channel_multiplier=2,
    bg_upsampler=None,
)

!pip install -q diffusers transformers accelerate gradio torch

import torch
from diffusers import AutoPipelineForImage2Image

# Load the fast Stable Diffusion XL Image-to-Image pipeline in 16-bit precision
pipe = AutoPipelineForImage2Image.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0",
    torch_dtype=torch.float16,
    variant="fp16"
).to("cuda")

print("AI Model Loaded Successfully!")

import torch
from diffusers import AutoPipelineForImage2Image
from diffusers.utils import load_image
import os
from PIL import Image

# -------------------------------------------------------------------
# Configuration - You can change the "Style Prompt" later
# -------------------------------------------------------------------
# This prompt tells the AI how to transform the person's face.
# Change "Cyberpunk" to "Oil Painting", "Anime Style", or "Zombie" for different events.
STYLE_PROMPT = "Transform this individual into a futuristic corporate cyberpunk portrait. Maintain face shape. Add neon lighting and futuristic tech jacket."

# The model we loaded in Step 3
INPUT_FILENAME = "input_photo.jpg"
OUTPUT_FILENAME = "transformed_portrait.png"


def run_transformation():
    """Runs the full transformation pipeline."""

    # 1. Check if the input photo exists
    if not os.path.exists(INPUT_FILENAME):
        print(f"ERROR: No image found. You need to upload an image named '{INPUT_FILENAME}'.")
        return

    print(f"Beginning AI transformation... (This might take 10-20 seconds)")

    # 2. Load the pipeline (assuming pipe is in global scope from Step 3)
    # If Step 3 did not run correctly, uncomment the next block:
    # try:
    #    pipe
    # except NameError:
    #    from diffusers import AutoPipelineForImage2Image
    #    pipe = AutoPipelineForImage2Image.from_pretrained(
    #        "stabilityai/stable-diffusion-xl-refiner-1.0",
    #        torch_dtype=torch.float16,
    #        variant="fp16"
    #    ).to("cuda")

    # 3. Process the Image-to-Image Transformation
    init_image = load_image(INPUT_FILENAME).convert("RGB")

    # We use high denoising strength to dramatically alter the face/style while keeping the pose.
    # strength=0.7 means 70% of the image is reshaped by the AI.
    result_image = pipe(
        STYLE_PROMPT,
        image=init_image,
        strength=0.70,
        guidance_scale=12.5,
        num_inference_steps=25,
        generator=torch.manual_seed(42) # Keep seed fixed for consistent testing
    ).images[0]

    # 4. Save the transformed image
    result_image.save(OUTPUT_FILENAME)
    print(f"SUCCESS! Transformed image saved as '{OUTPUT_FILENAME}'.")

    # 5. Display the result directly in Colab
    display(result_image)

if __name__ == "__main__":
    run_transformation()

!pip install -q insightface onnxruntime-gpu opencv-python pillow gradio

import insightface
from insightface.app import FaceAnalysis
import cv2
import numpy as np
import os

print("1. Downloading InSwapper Model...")
# Download the model directly using wget
!wget -O inswapper_128.onnx https://github.com/deepinsight/insightface/releases/download/v0.7/inswapper_128.onnx

print("\n2. Initializing Face Analysis...")
app = FaceAnalysis(name='buffalo_l', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640))

print("\n3. Loading Swapper Model...")
# Load the model directly from the file path
swapper = insightface.model_zoo.get_model('inswapper_128.onnx', download=False, providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])

print("\nFace Swapping Models Loaded Successfully!")

import os
import cv2
import insightface
from PIL import Image
import matplotlib.pyplot as plt

# 1. Helper function to safely find the uploaded file regardless of extension
def find_image(base_name):
    possible_extensions = ['.jpg', '.jpeg', '.png', '.JPG', '.JPEG', '.PNG']
    for ext in possible_extensions:
        full_path = base_name + ext
        if os.path.exists(full_path):
            return full_path
        if os.path.exists(base_name): # Direct filename check
            return base_name
    return None

source_path = find_image('input_photo')
target_path = find_image('download')

# 2. Check if files were located correctly
if not source_path:
    print("ERROR: Could not find 'input_photo' in Colab files!")
elif not target_path:
    print("ERROR: Could not find 'download' image in Colab files!")
else:
    print(f"Loading source: {source_path}")
    print(f"Loading target: {target_path}")

    source_img = cv2.imread(source_path)
    target_img = cv2.imread(target_path)

    # 3. Detect faces in both images
    source_faces = app.get(source_img)
    target_faces = app.get(target_img)

    if len(source_faces) == 0:
        print("Error: No face detected in your source selfie.")
    elif len(target_faces) == 0:
        print("Error: No face detected in the target stylized image.")
    else:
        # Select the main face from each image
        source_face = source_faces[0]
        target_face = target_faces[0]

        # 4. Perform the Face Swap
        result_img = swapper.get(target_img, target_face, source_face, paste_back=True)

        # 5. Save and Display the Result
        output_filename = 'faceswap_result.png'
        cv2.imwrite(output_filename, result_img)
        print(f"\nSUCCESS! Swapped image saved as '{output_filename}'.")

        # Display image directly in Colab
        result_rgb = cv2.cvtColor(result_img, cv2.COLOR_BGR2RGB)
        plt.figure(figsize=(8, 10))
        plt.imshow(result_rgb)
        plt.axis('off')
        plt.show()

import urllib.request

# Download 3 high-quality preset templates directly into your booth
preset_urls = {
    "cyberpunk.jpg": "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&q=80",
    "royal.jpg": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80",
    "business.jpg": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80"
}

for filename, url in preset_urls.items():
    urllib.request.urlretrieve(url, filename)
    print(f"Downloaded preset template: {filename}")

print("\nAll sample event templates are ready!")

import urllib.request

# Define custom preset template URLs
preset_urls = {
    # Traditional Saudi Ghutra/Shemagh Portrait
    "saudi_traditional.jpg": "https://img.freepik.com/free-photo/portrait-man-wearing-traditional-saudi-arabian-clothing_14117-839518.jpg",

    # Future Vision 2030 Astronaut Suit
    "vision_2030_astronaut.jpg": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",

    # Futuristic Cyberpunk
    "cyberpunk.jpg": "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&q=80"
}

# Download template images into your Colab workspace
for filename, url in preset_urls.items():
    try:
        urllib.request.urlretrieve(url, filename)
        print(f"✅ Successfully downloaded preset: {filename}")
    except Exception as e:
        print(f"❌ Failed to download {filename}: {e}")

print("\nCustom Saudi presets are updated and ready!")

import urllib.request

# URL for a clean camera shutter sound effect
sound_url = "https://soundbible.com/grab.php?id=563&type=mp3"

# Add a User-Agent so the website allows Python to download it
req = urllib.request.Request(
    sound_url,
    headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
)

with urllib.request.urlopen(req) as response, open("shutter.mp3", "wb") as out_file:
    out_file.write(response.read())

print("✅ Sound effect 'shutter.mp3' downloaded successfully!")

!pip install -q gfpgan
!wget -O GFPGANv1.4.pth https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth

from gfpgan import GFPGANer

# Initialize GFPGAN Restorer
# scale=2 upscales the restored face region for crispness
restorer = GFPGANer(
    model_path='GFPGANv1.4.pth',
    upscale=2,
    arch='clean',
    channel_multiplier=2,
    bg_upsampler=None
)
print("✅ High-Resolution GFPGAN Restorer Loaded!")

# 1. Patch the missing torchvision module in basicsr automatically
!pip install -q codeformer-pip
!python -c "import site, os; p=os.path.join(site.getsitepackages()[0],'basicsr/data/degradations.py'); open(p,'w').write(open(p).read().replace('functional_tensor','functional')) if os.path.exists(p) else None"

# 2. Download CodeFormer weights
!wget -O codeformer.pth https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth

import torch
from codeformer.app import inference_app

print("✅ High-Definition CodeFormer Restorer Ready!")

import gradio as gr
import cv2
import insightface
import numpy as np
from PIL import Image
import os

def load_target_image(file_path):
    if not os.path.exists(file_path):
        return None
    try:
        pil_img = Image.open(file_path).convert('RGB')
        return cv2.cvtColor(np.array(pil_img), cv2.COLOR_RGB2BGR)
    except Exception as e:
        print(f"Error loading {file_path}: {e}")
        return None

def process_hd_face_swap_stable(user_photo, style_choice, enable_hd=True):
    """
    Robust Face Swap + HD Enhancement using Native OpenCV.
    Guaranteed zero dependency crashes.
    """
    if user_photo is None:
        return None, None, "Please upload a photo!"

    # Map selection to target image
    if style_choice == "Traditional Saudi Attire":
        target_img = load_target_image("saudi_custom.avif")
        if target_img is None:
            target_img = load_target_image("saudi_traditional.jpg")
    else:
        target_img = load_target_image("vision_2030_astronaut.jpg")

    if target_img is None:
        return None, None, "Error: Template image missing in Colab workspace."

    # Convert uploaded image to OpenCV format
    source_img = cv2.cvtColor(np.array(user_photo), cv2.COLOR_RGB2BGR)

    # Detect faces
    source_faces = app.get(source_img)
    target_faces = app.get(target_img)

    if len(source_faces) == 0 or len(target_faces) == 0:
        return cv2.cvtColor(target_img, cv2.COLOR_BGR2RGB), None, "Face detection failed! Ensure face is clearly visible."

    # 1. Perform Face Swap
    swapped_img = swapper.get(target_img, target_faces[0], source_faces[0], paste_back=True)

    # 2. Apply HD Detail Enhancement (Sharpening + Contrast)
    if enable_hd:
        # Sharpens facial features (eyes, beard, nose) without breaking pixel matrices
        enhanced_img = cv2.detailEnhance(swapped_img, sigma_s=10, sigma_r=0.15)
        # Smooth color blending slightly for clean skin tone
        final_img = cv2.bilateralFilter(enhanced_img, d=5, sigmaColor=50, sigmaSpace=50)
    else:
        final_img = swapped_img

    # Convert OpenCV BGR format back to RGB for browser rendering
    result_rgb = cv2.cvtColor(final_img, cv2.COLOR_BGR2RGB)

    return result_rgb, "shutter.mp3", "✨ HD Transformation Complete!"

# Build Kiosk UI
with gr.Blocks(title="Saudi AI Stable HD Kiosk") as demo:
    gr.Markdown("# 🇸🇦 AI Event Kiosk (Ultra-HD & Audio Enabled)")

    with gr.Row():
        with gr.Column():
            input_image = gr.Image(type="pil", label="1. Take / Upload Photo")
            style_dropdown = gr.Dropdown(
                choices=["Traditional Saudi Attire", "Vision 2030 Astronaut"],
                value="Traditional Saudi Attire",
                label="2. Choose Style Preset"
            )
            hd_checkbox = gr.Checkbox(label="Enable HD Detail Sharpener", value=True)
            submit_btn = gr.Button("📸 Print / Transform HD", variant="primary")
            status_output = gr.Textbox(label="System Status", value="Ready")

        with gr.Column():
            output_image = gr.Image(label="HD Transformed Output")
            audio_output = gr.Audio(label="Audio Feedback", autoplay=True, visible=True)

    submit_btn.click(
        fn=process_hd_face_swap_stable,
        inputs=[input_image, style_dropdown, hd_checkbox],
        outputs=[output_image, audio_output, status_output]
    )

demo.launch(share=True, debug=True)
